config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'



  root 'home#index'
  devise_for :users
  resources :authors
  resources :genres
  resources :books
#  resources :confirmations
  resources :loans do
    member do
      get :cancel
      get :acept
      get :return
    end
  end
  namespace :admin do
    resources :users
  end

  resources :users do
    member do
      get :confirm_email
    end
  end



  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


end

app/models/author.rb
class Author < ApplicationRecord

  extend FriendlyId
  friendly_id :first_name, :use => :slugged

  has_one_attached :photo
  has_many :books, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :date_of_birth, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :find_one, only: [:show, :edit, :update, :destroy] # this allows to add  find_one in the beginning of the methods mentioned
  before_action :authenticate_user!
  before_action :check_user_role, only: [:edit, :update, :new]

  def index
    @authors = Author.all
  end

  def show
    @author = Author.friendly.find(params[:id])

    puts "author: #{@author.id}"
    @books = Book.friendly.where(author_id: @author.id)
  end


  def new
    @author = Author.new
  end

  def edit
    @author = Author.friendly.find(params[:id])
  end

  def update
    @author = Author.friendly.find(params[:id])

    @author.update(author_params)

    redirect_to author_path(@author)
  end


  def create
    @author = Author.create(author_params)

    redirect_to authors_path
  end

  def destroy


    @author = Author.friendly.find(params[:id])
    @author.destroy
    # if @author.book.empty?
    #   flash[:notice] = "Author deleted successfully"
    # else
    #   flash[:alert] = "Cannot delete author with associated books"
    # end

    redirect_to authors_path
  end


  private
  def author_params
    params.require(:author).permit(:first_name, :last_name, :date_of_birth, :nationality, :photo, :biography, :date_of_death)
  end

  def find_one
    @author = Author.friendly.find(params[:id])
  end





end

app/helpers/author_helper.rb
module AuthorHelper


end

app/views/authors/edit.html.erb
<%= render 'shared/header_admin' if user_signed_in?  %>


    <%= link_to "Back to authors", authors_path, class:'btn btn-light m-3 bi bi-arrow-90deg-left text-dark'  %>

<div class="container rounded">

    <h3 class="text-center">Edit <%= "#{@author.first_name} #{@author.last_name}"%></h3>

    <%= render 'shared/authors/form' if user_signed_in? && current_user.role_id == 1 || 3  %>
</div>

app/views/authors/index.html.erb
<%= render 'shared/header_admin' if user_signed_in?  %>

<%= link_to "New Author", new_author_path, class: 'btn btn-light m-3 bi  bi-plus-lg text-dark' if current_user.role_id == 3 || 2%>

<div class="container p-4 mt-4">
  <h1 class="text-center">Authors</h1>
  <div class="row">

  <% @authors.each do |author| %>
    <div class="col mb-3">
      <div class="card " style="width: 155px;">
          
          <% if author.photo.attached? %>
            <%= image_tag(author.photo,  class: 'card-img-top', height: "155px")  %>
          <% else %>
            <%= image_tag 'default.jpg', class: 'card-img-top' %>
          <% end %>
          
        <div class="card-body">
          <%= link_to "#{author.first_name} #{author.last_name}", author_path(author) ,class: 'card-text' %>
        </div>
      </div>
    </div>
    
     
  <% end %>

  </div>
</div>

app/views/authors/new.html.erb
<%= render 'shared/header_admin' if user_signed_in?   %>
    <%= link_to "Back to authors", authors_path, class:'btn btn-light m-3 bi bi-arrow-90deg-left text-dark  text-light'  %>
    
<div class="container rounded">

    <h3 class="text-center">Create an Author</h3>

    <%= render 'shared/authors/form' if user_signed_in? && current_user.role_id == 1 || 3  %>
</div>

app/views/authors/show.html.erb
<%= render 'shared/header_admin' if user_signed_in?   %>

<%=  link_to 'Back', authors_path, class: 'btn btn-light m-3 bi bi-arrow-90deg-left text-dark  text-light' %>
<div class="container rounded p-2 ">
    <div class="row  ">
        <div class="col-1 offset-1 m-3 ">
            <%= image_tag(@author.photo, class: 'rounded', width: '200px') if @author.photo.attached?%>
        </div>
        <div class="col-8 offset-1">

            <h1>
                <%= "#{@author.first_name} #{@author.last_name}" %>
                <%= "(#{@author.date_of_birth.year} -   #{@author.date_of_death.present? ? @author.date_of_death.year : 'now'})"%> 
            </h1>

            <p>
                <%= @author.nationality%>
            </p>
            <p>
                <%= @author.biography%>
            </p>

            <%= button_to 'Remove', author_path(@author), method: 'delete',class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' } if current_user.role_id == 1 || 3 %>

            <%= link_to 'Edit', edit_author_path, class:'btn btn-outline-primary mt-3' if current_user.role_id == 1 || 3%>
        </div>
    </div>
</div>


<div class="container p-4 mt-4">
  <h1 class="text-center">Books of <%= @author.full_name %></h1>
  <div class="row">

  <% @books.each do |book| %>
    <div class="col-2 mb-3">
      <div class="card " style="width: 155px;">
          
          <% if book.photo.attached? %>
            <%= image_tag(book.photo,  class: 'card-img-top', height: "200px")  %>
          <% else %>
            <%= image_tag 'defaultBook.jpg', class: 'card-img-top' %>
          <% end %>
          
        <div class="card-body">
         <strong> <%= link_to "#{book.title} (#{book.author.first_name} #{book.author.last_name})", book_path(book) ,class: 'card-text' %></strong>

        </div>
      </div>
    </div>
    
     
  <% end %>

  </div>
</div>