config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'



  root 'home#index'
  devise_for :users
  resources :authors
  resources :genres
  resources :books
#  resources :confirmations
  resources :loans do
    member do
      get :cancel
      get :acept
      get :return
    end
  end
  namespace :admin do
    resources :users
  end

  resources :users do
    member do
      get :confirm_email
    end
  end



  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord

  extend FriendlyId
  friendly_id :first_name, :use => :slugged

  has_one_attached :photo
  has_many :books, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :date_of_birth, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/book.rb
class Book < ApplicationRecord

  extend FriendlyId

  friendly_id :title, :use => :slugged


  belongs_to :author
  has_one_attached :photo
  has_many :loans

  has_and_belongs_to_many :genre


    # Method to acept a loan
    def change_copies(copies)

      update(copies_available: copies)
    end

    def self.ransackable_attributes(auth_object = nil)
      ["author_id",  "synopsis", "title"]
    end
    def self.ransackable_associations(auth_object = nil)
      ["author", "genre"]

    end



  validates :title, presence: true
  validates :isbn, presence: true
  validates :publication_year, presence: true
  validates :copies_available, presence: true
  validates :author_id, presence: true

  validates :synopsis, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord

  extend FriendlyId
  friendly_id :name, :use => :slugged

  has_and_belongs_to_many :book
  has_one_attached :photo


  validates :name, presence: true
  def self.ransackable_attributes(auth_object = nil)
    [ "id", "name"]
  end
end

app/models/loan.rb
class Loan < ApplicationRecord


  belongs_to :book
  belongs_to :user
  belongs_to :status

  validates :loan_date, :due_date, presence: true

  # Method to create a new loan
  def self.add_loan(book_id, user_id, loan_date, due_date, comments = nil)
    status = Status.find_by(name: 'requested')
    create(book_id: book_id, user_id: user_id, status_id: status.id, loan_date: loan_date, due_date: due_date, comments: comments)
  end

  # Method to acept a loan
  def acept_loan

   update(status: Status.find_by(name: 'active'), returned_date: Date.today)
  end
  # Method to cancel a loan
  def cancel_loan

    update(status: Status.find_by(name: 'cancelled'), returned_date: Date.today)
  end

  # Method to cancel a loan
  def return_loan

    update(status: Status.find_by(name: 'returned'), returned_date: Date.today)
  end

end

app/models/role.rb
class Role < ApplicationRecord

  has_many :users, dependent: :destroy

end

app/models/status.rb
class Status < ApplicationRecord
  has_many :loans
end

app/models/user.rb
class User < ApplicationRecord


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :validatable,
         :trackable, :confirmable, :timeoutable, timeout_in: 20.minutes
  belongs_to :role

  def after_sign_in_path_for(resource)
    if resource.confirmed?
      super # Redirige al destino por defecto (configurado en Devise)
    else
      new_user_confirmation_path # Redirige a la página de confirmación
    end
  end
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end
# app/models/user.rb

app/controllers/books_controller.rb
class BooksController < ApplicationController


  before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update]
  before_action :check_confirmed



  def index
    @books = Book.includes(:author, :genre)
  end

  def show

    @book = Book.includes(:author, :genre).friendly.find(params[:id])
    puts "copies: #{@book.copies_available}"

  end

  def new
    @book = Book.new
    @genres = Genre.all
    @authors = Author.all
  end

  def edit
    @genres = Genre.all
    @authors = Author.all
  end

  def destroy
    @book = Book.friendly.find(params[:id])

    @book.destroy

    redirect_to books_path
  end


  def create
    puts book_params
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path , notice: 'El libro fue creado exitosamente.'
    else
      @genres = Genre.all
      puts "Error: #{@book.errors.full_messages}"
      render :new, notice: @book.errors.full_messages[0]
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'El libro fue actualizado exitosamente.'
    else
      @genres = Genre.all
      render :edit
    end
  end


  private

  def set_book
    @book = Book.friendly.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :isbn, :publication_year, :copies_available, :synopsis, :author_id, :photo, genre_ids: [])
  end


end

app/controllers/home_controller.rb
require 'json'

class HomeController < ApplicationController
  before_action :authenticate_user!



  def index



    @books = Book.limit(6)  # Retrieve only the first 6 books
    @genres = Genre.limit(6)  # Retrieve only the first 6 books
    @authors = Author.limit(6)  # Retrieve only the first 6 books

    # Depuración adicional
    # ... (your debugging code can remain here)
    #
    #
    @user = User.find(current_user.id)
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [ :cancel, :acept, :return]
  before_action :authenticate_user!
  before_action :check_user_role, only: [:cancel, :acept ]
  before_action :check_user_role

  # GET /loans
  def index
    @loans = Loan.all.order(due_date: :desc, status_id: :asc)
  end


  # GET /loans/new
  def new
    @loan = Loan.new
    @user = User.where(role_id: '2')

  end

  # PATCH /loans/:id/cancel
  def acept
    if @loan.acept_loan
      redirect_to loans_path, notice: 'Loan was successfully acepted.'
    else
      render :index
    end
  end

    # PATCH /loans/:id/cancel
    def return
      @book = Book.friendly.find(@loan.book_id)
      if @loan.return_loan

        @book.change_copies(@book.copies_available + 1)

        redirect_to loans_path, notice: 'Loan was successfully canceled.'
      else
        render :index
      end
    end


  # POST /loans
  def create
    @user = User.find(loan_params[:user_id])
    @book = Book.friendly.find(loan_params[:book_id])
    @loan = Loan.add_loan(loan_params[:book_id], loan_params[:user_id], loan_params[:loan_date], loan_params[:due_date], loan_params[:comments])

    servibook_mail = ServiBookMail.new

    msg = ''



    if @loan.save
      @book.change_copies(@book.copies_available - 1)


      mail_content = {
        name: @user.name,
        book: @book.title,
        address: @user.address,
        start_date:  Date.parse(loan_params[:loan_date]).strftime("%d-%m-%Y"),
        end_date: Date.parse(loan_params[:due_date]).strftime("%d-%m-%Y"),
        email: @user.email,
        loan: @loan.id

      }


      @response = servibook_mail.send_invoice(mail_content)

      if @response.success?
        msg = "Invoice sent to your email #{@user.email}"
      else

        msg = "An error occurred: "
      end




      if @user.role_id == 2
        redirect_to book_path(loan_params[:book_id]), notice: "Loan was successfully created. #{msg}"
      else
        redirect_to loans_path, notice: "Loan was successfully created. #{msg}"

      end

    else
      render :new
    end

  end

  # PATCH /loans/:id/cancel
  def cancel
    @book = Book.find(@loan.book_id)

    if @loan.cancel_loan
      @book.change_copies(@book.copies_available + 1)

      redirect_to loans_path, notice: 'Loan was successfully canceled.'
    else
      render :index
    end
  end

  private

  def set_loan
    @loan = Loan.find(params[:id])
  end

  def loan_params
    params.require(:loan).permit(:book_id, :user_id, :loan_date, :due_date, :comments)
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/author_helper.rb
module AuthorHelper


end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/shared/_confirm_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Por favor, confirma tu correo electrónico para acceder a todas las funciones.</h1>
    <%= link_to 'Reenviar confrirmacion', new_user_confirmation_path %>

    </div>
  </div>
</div>
  

app/views/shared/_header_admin.html.erb
<nav class="navbar bg-body-tertiary d-flex">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
        <%= image_tag 'logo.png' , class: "logo", width: "50", height: "50" %>
        <strong class="servi">
        Servi
        </strong>
        <strong class="book">
        Books
        </strong>
    </a>
    <div class="w-50">

        <%= render 'search/form' %>
    </div>


    <ul class="nav justify-content-end">
        <li class="nav-item">
            <li><%= link_to "Books", books_path , class: "nav-link active"%></li>
        </li>
        <li class="nav-item">
            <li><%= link_to "Loans", loans_path , class: "nav-link active"%></li>
        </li>
        <li class="nav-item">
            <li><%= link_to "Genres", genres_path , class: "nav-link active"%></li>
        </li>
        <li class="nav-item">
            <li><%= link_to "Authors", authors_path , class: "nav-link active"%></li>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">
                <%= current_user.name%>
            </a>
            <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/users/edit">Profile</a></li>
            <li><%= link_to "Admin users", admin_users_path , class: "nav-link active" if current_user.role_id == 3%></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete , class: "dropdown-item"%></li>
            </ul>
        </li>
    </ul>
  </div>
    <%=raw @html_quote%>
    

</nav>

app/views/shared/_principal_page.html.erb
<div class="container mt-5">
  
    <div class="column">
      <div class="w-100" style="">
       <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">

            <div class="carousel-item active" data-bs-interval="100000">
              <%= image_tag 'carrousel_2.jpg' , class: "d-block w-100", width: "100", height: "500" %>
            </div>
            <div class="carousel-item active" data-bs-interval="100000">
              <%= image_tag 'carrousel_3.jpg' , class: "d-block w-100", width: "100", height: "500" %>
            </div>
            <div class="carousel-item active" data-bs-interval="100000">
              <%= image_tag 'carrousel_4.jpg' , class: "d-block w-100", width: "100", height: "500" %>
            </div>
            <div class="carousel-item active" data-bs-interval="100000">
              <%= image_tag 'carrousel_5.jpg' , class: "d-block w-100", width: "100", height: "500" %>
            </div>
            <div class="carousel-item active" data-bs-interval="100000">
              <%= image_tag 'carrousel_6.jpg' , class: "d-block w-100", width: "100", height: "500" %>
            </div>

          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </div>
  
</div>


<%= render 'shared/lists/list_books'  %>

app/views/shared/lists/_list_books.html.erb
<div class="container p-4 mt-4">

  <div class="row">

  <% @books.each do |book| %>
    <div class="col-2 mb-3">
      <div class="card " style="width: 155px;">
          
          <% if book.photo.attached? %>
            <%= image_tag(book.photo,  class: 'card-img-top', height: "200px")  %>
          <% else %>
            <%= image_tag 'defaultBook.jpg', class: 'card-img-top' %>
          <% end %>
          
        <div class="card-body">
         <strong> <%= link_to "#{book.title} (#{book.author.first_name} #{book.author.last_name})", book_path(book) ,class: 'card-text' %></strong>

        </div>
      </div>
    </div>
    
     
  <% end %>


  </div>
</div>