config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'



  root 'home#index'
  devise_for :users
  resources :authors
  resources :genres
  resources :books
#  resources :confirmations
  resources :loans do
    member do
      get :cancel
      get :acept
      get :return
    end
  end
  namespace :admin do
    resources :users
  end

  resources :users do
    member do
      get :confirm_email
    end
  end



  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


end

app/models/user.rb
class User < ApplicationRecord


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :validatable,
         :trackable, :confirmable, :timeoutable, timeout_in: 20.minutes
  belongs_to :role

  def after_sign_in_path_for(resource)
    if resource.confirmed?
      super # Redirige al destino por defecto (configurado en Devise)
    else
      new_user_confirmation_path # Redirige a la página de confirmación
    end
  end
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end
# app/models/user.rb

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
      @users = User.includes(:role)
    end

    def show
      @user = User.find(params[:id])
    end

    def new
      @user = User.new
      @roles = Role.all
    end

    def edit
      @roles = Role.all
    end

    def destroy
      @user = User.find(params[:id])

      if @user.destroy
        redirect_to admin_users_path, notice: 'El usuario fue eliminado exitosamente.'
      else
        redirect_to admin_users_path, alert: 'El usuario no se pudo eliminar, verifica que no sea administrador o tenga registros asociados.'
      end
    rescue ActiveRecord::InvalidForeignKey => e
      puts e
      redirect_to admin_users_path, alert: "El usuario no se pudo eliminar, verifica que no sea administrador o tenga registros asociados."
    end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to admin_users_path, notice: 'El usuario fue creado exitosamente.'
      else
        @roles = Role.all
        render :new
      end
    end

    def update
      if @user.update(user_params)
        redirect_to admin_users_path, notice: 'El usuario fue actualizado exitosamente.'
      else
        @roles = Role.all
        puts @user.errors.full_messages
        render :edit
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      permitted_params = [:name, :email, :address, :phone, :role_id]

      if params[:user][:password].present?
        permitted_params << :password
        permitted_params << :password_confirmation
      end

      params.require(:user).permit(permitted_params)
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/edit.html.erb
<%= render 'shared/header_admin' if user_signed_in?  %>

<%= stylesheet_link_tag 'auth' %>
<%=  link_to 'Back', admin_users_path, class: 'btn btn-light m-3 bi bi-arrow-90deg-left text-dark  text-light' %>

<div class="container-md d-flex justify-content-center rounded">
  <div class="row">
    <div class="col-12 text-center mt-3">
      <%= image_tag "logo.png", alt: "My Logo", class: "logo", width: "100", height: "100" %>
      <h2>Create User</h2>

    </div>


<%= form_with(model: @user, local: true, url: admin_user_path(@user), method: 'PATCH') do |f| %>

   

    <div class="row">
      <div class="col-6">
        <div class="field">
          <p><%= f.label :name , class: "form-label" %></p>
          <p><%= f.text_field :name, autofocus: true, autocomplete: "name" , class: "form-control" %></p>
        </div>

        <div class="field">
          <p><%= f.label :email , class: "form-label" %></p>
          <p><%= f.email_field :email, autofocus: true, autocomplete: "email" , class: "form-control" %></p>
        </div>



      </div>
      <div class="col-6">

        <div class="field">
          <p><%= f.label :phone , class: "form-label" %></p>
          <p><%= f.phone_field :phone, autofocus: true, autocomplete: "phone" , class: "form-control" %></p>
        </div>

        <div class="field">
          <p><%= f.label :address , class: "form-label" %></p>
          <p><%= f.text_field :address, autofocus: true, autocomplete: "address" , class: "form-control" %></p>
        </div>
      </div>
      

    </div>
     <div class="row">
      </div>

    <div class="row">

      <div class="col-7 ">
        <div class="field">
          <p><%= f.label :password , class: "form-label"%> <i>(leave blank if you don't want to change it)</i></p>
          <p><%= f.password_field :password, autocomplete: "new-password" , class: "form-control"%></p>
          <% if @minimum_password_length %>
          <% end %>
          <div id="passwordHelpInline" class="form-text"></div> <!-- Contenedor para mostrar las acciones que faltan realizar en la contraseña -->

        </div>
        </div>
      <div class="col-5">

        <div class="field">
            <br>
          <p><%= f.label :password_confirmation , class: "form-label"%></p>
          <br>
          <p><%= f.password_field :password_confirmation, autocomplete: "new-password" , class: "form-control"%></p>
        </div>
        </div>


    

    </div>
    <div class="col-12 text-center">
          <div class="col">
        <div class="col">
          <p><%= f.label :role, class: "form-label" %></p>
          <%= f.collection_radio_buttons :role_id, @roles, :id, :name, include_hidden: false do |b| %>
            <div class="form-check form-check-inline">
              <%= b.radio_button(class: "form-check-input") %>
              <%= b.label(class: "form-check-label") %>
            </div>
          <% end %>
        </div>
        

      </div>
      
      <div class="actions">
      <%= f.submit "Update" , class: "btn btn-dark btn-bg mb-3"%>

      </div>

      <div>
      </div>
    </div>
  <% end %>


  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const passwordField = document.querySelector('#user_password');
    const enableButton = document.querySelector('#enable');
    const passwordStrength = document.querySelector('#passwordHelpInline');
    const passwordConfirmation = document.querySelector('#user_password_confirmation');

    passwordField.addEventListener('input', function() {
      const password = this.value;
      const actions = [];

      // Verificar la fortaleza de la contraseña
      if (password.length < 8) {
        actions.push("More than 8 characters.");
      }
      if (!/[A-Z]/.test(password)) {
        actions.push('More than 1 uppercase.');
      }
      if (!/[a-z]/.test(password)) {
        actions.push('More than 1 lowercase.');
      }
      if (!/[0-9]/.test(password)) {
        actions.push('More than 1 number.');
      }
      if (!/[^a-zA-Z\d]/.test(password)) {
        actions.push('More than 1 special character (not letters or numbers).');
      }
      // Validación para evitar números consecutivos
      if (/(\d)\1\1|012|123|234|345|456|567|678|789|890|901|098|987|876|765|654|543|432|321|210|109/.test(password)) {
        actions.push('No consecutive numbers.');
      }

      // Validación para evitar letras consecutivas
      if (/(abc|bcd|cde|def|efg|fgh|ghi|hij|ijk|jkl|klm|lmn|mno|nop|opq|pqr|qrs|rst|stu|tuv|uvw|vwx|wxy|xyz|ABC|BCD|CDE|DEF|EFG|FGH|GHI|HIJ|IJK|JKL|KLM|LMN|MNO|NOP|OPQ|PQR|QRS|RST|STU|TUV|UVW|VWX|WXY|XYZ)/.test(password)) {
        actions.push('No consecutive letters.');
      }

      if (checkPass(password, passwordConfirmation.value)) {
        actions.push('Passwords must match.');
      }

      // Mostrar las acciones que faltan realizar en la contraseña
      if (actions.length > 0) {
        passwordStrength.hidden = false;
        passwordStrength.innerHTML = actions.map(action => `<p class="text-danger">${action}</p>`).join('');
        enableButton.disabled = true;
      } else {
        passwordStrength.hidden = true;
        enableButton.disabled = false;
        passwordStrength.innerHTML = '';
      }
    });

    passwordConfirmation.addEventListener('input', function() {
      const passwordConfirm = this.value;
      const password = passwordField.value;
      const actions = [];
      if (checkPass(password, passwordConfirmation.value)) {
        actions.push('Passwords must match.');
      }

      // Mostrar las acciones que faltan realizar en la contraseña
      if (actions.length > 0) {
        passwordStrength.hidden = false;
        passwordStrength.innerHTML = actions.map(action => `<p class="text-danger">${action}</p>`).join('');
        enableButton.disabled = true;
      } else {
        passwordStrength.hidden = true;
        enableButton.disabled = false;
        passwordStrength.innerHTML = '';
      }
    });

    function checkPass(pass, confirmPass) {
      return pass !== confirmPass;
    }
  });
</script>

app/views/admin/users/index.html.erb
<%= render 'shared/header_admin' if user_signed_in?  %>

<%= link_to "New user", new_admin_user_path, class: 'btn btn-light m-3 bi  bi-plus-lg text-dark' if current_user.role_id == 1 || 3%>

<div class="container p-4 mt-4">
  <h1 class="text-center">Users</h1>
  <div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Address</th>
                <th scope="col">Role</th>
                <th></th>
                <th></th>


            </tr>
        </thead>
        <tbody>

            <% @users.each do |u| %>
                <tr>
                    <td>
                        <%= u.id%>
                    </td>

                    <td>
                        <%= u.name%>
                    </td>
                    <td>
                        <%= u.email%>
                    </td>
                    <td>
                        <%= u.phone%>
                    </td>
                    <td>
                        <%= u.address%>
                    </td>
                    <td>
                        <%= u.role.name%>
                    </td>

                    <td>

                                                <!-- Modal -->
                        <div class="modal fade" id="exampleModal<%=u.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">Are you sure?</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                By deleting the account ALL YOUR DATA will be deleted
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                <%= button_to 'Acept', admin_user_path(u), method: 'delete',class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' } if current_user.role_id == 1 || 3 %>
                            </div>
                            </div>
                        </div>
                        </div>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal<%=u.id%>">
                        Delete
                        </button>
                      
                    </td>
                    <td>
                        <%= link_to 'Edit', edit_admin_user_path(u), class:'btn btn-outline-primary ' if current_user.role_id == 1 || 3%>
                    </td>

                </tr>
                  
  
            <% end %>

        </tbody>
    </table>

  </div>
</div>

app/views/admin/users/new.html.erb
<%= render 'shared/header_admin' if user_signed_in?  %>

<%= stylesheet_link_tag 'auth' %>
<%=  link_to 'Back', admin_users_path, class: 'btn btn-light m-3 bi bi-arrow-90deg-left text-dark  text-light' %>

<div class="container-md d-flex justify-content-center rounded">
  <div class="row">
    <div class="col-12 text-center mt-3">
      <%= image_tag "logo.png", alt: "My Logo", class: "logo", width: "100", height: "100" %>
      <h2>Create User</h2>
    </div>

    <%= form_with(model: @user, local: true, url: admin_users_path) do |f| %>
      <div class="row">
        <div class="col">
          <div class="field">
            <p><%= f.label :name, class: "form-label" %></p>
            <p><%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %></p>
          </div>
          
          <div class="field">
            <p><%= f.label :email, class: "form-label" %></p>
            <p><%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %></p>
          </div>
          
          <div class="field">
            <p><%= f.label :password, class: "form-label" %></p>
            <p><%= f.password_field :password, autocomplete: "new-password", class: "form-control" %></p>
          </div>
        </div>

        <div class="col">
          <div class="field">
            <p><%= f.label :address, class: "form-label" %></p>
            <p><%= f.text_field :address, autofocus: true, autocomplete: "address", class: "form-control" %></p>
          </div>
          
          <div class="field">
            <p><%= f.label :phone, class: "form-label" %></p>
            <p><%= f.phone_field :phone, autofocus: true, autocomplete: "phone", class: "form-control" %></p>
          </div>
          
          <div class="field">
            <p><%= f.label :password_confirmation, class: "form-label" %></p>
            <p><%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control"%></p>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="col">
          <p><%= f.label :role, class: "form-label" %></p>
          <%= f.collection_radio_buttons :role_id, @roles, :id, :name, include_hidden: false do |b| %>
            <div class="form-check form-check-inline">
              <%= b.radio_button(class: "form-check-input") %>
              <%= b.label(class: "form-check-label") %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <div id="passwordHelpInline" class="form-text bg-secondary rounded p-3" hidden=true></div>
        </div>
      </div>
      
      <div class="row">
        <div class="col text-center">
          <div class="actions">
            <%= f.submit "Done", id: "enable", disabled: true, class: "btn btn-dark mb-3", data: { turbo: false } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const passwordField = document.querySelector('#user_password');
    const enableButton = document.querySelector('#enable');
    const passwordStrength = document.querySelector('#passwordHelpInline');
    const passwordConfirmation = document.querySelector('#user_password_confirmation');

    passwordField.addEventListener('input', function() {
      const password = this.value;
      const actions = [];

      // Verificar la fortaleza de la contraseña
      if (password.length < 8) {
        actions.push("More than 8 characters.");
      }
      if (!/[A-Z]/.test(password)) {
        actions.push('More than 1 uppercase.');
      }
      if (!/[a-z]/.test(password)) {
        actions.push('More than 1 lowercase.');
      }
      if (!/[0-9]/.test(password)) {
        actions.push('More than 1 number.');
      }
      if (!/[^a-zA-Z\d]/.test(password)) {
        actions.push('More than 1 special character (not letters or numbers).');
      }
      // Validación para evitar números consecutivos
      if (/(\d)\1\1|012|123|234|345|456|567|678|789|890|901|098|987|876|765|654|543|432|321|210|109/.test(password)) {
        actions.push('No consecutive numbers.');
      }

      // Validación para evitar letras consecutivas
      if (/(abc|bcd|cde|def|efg|fgh|ghi|hij|ijk|jkl|klm|lmn|mno|nop|opq|pqr|qrs|rst|stu|tuv|uvw|vwx|wxy|xyz|ABC|BCD|CDE|DEF|EFG|FGH|GHI|HIJ|IJK|JKL|KLM|LMN|MNO|NOP|OPQ|PQR|QRS|RST|STU|TUV|UVW|VWX|WXY|XYZ)/.test(password)) {
        actions.push('No consecutive letters.');
      }

      if (checkPass(password, passwordConfirmation.value)) {
        actions.push('Passwords must match.');
      }

      // Mostrar las acciones que faltan realizar en la contraseña
      if (actions.length > 0) {
        passwordStrength.hidden = false;
        passwordStrength.innerHTML = actions.map(action => `<p class="text-danger">${action}</p>`).join('');
        enableButton.disabled = true;
      } else {
        passwordStrength.hidden = true;
        enableButton.disabled = false;
        passwordStrength.innerHTML = '';
      }
    });

    passwordConfirmation.addEventListener('input', function() {
      const passwordConfirm = this.value;
      const password = passwordField.value;
      const actions = [];
      if (checkPass(password, passwordConfirmation.value)) {
        actions.push('Passwords must match.');
      }

      // Mostrar las acciones que faltan realizar en la contraseña
      if (actions.length > 0) {
        passwordStrength.hidden = false;
        passwordStrength.innerHTML = actions.map(action => `<p class="text-danger">${action}</p>`).join('');
        enableButton.disabled = true;
      } else {
        passwordStrength.hidden = true;
        enableButton.disabled = false;
        passwordStrength.innerHTML = '';
      }
    });

    function checkPass(pass, confirmPass) {
      return pass !== confirmPass;
    }
  });
</script>

app/views/admin/users/show.html.erb
<%= render 'shared/header_admin' if user_signed_in?   %>

<%=  link_to 'Back', admin_users_path, class: 'btn btn-light m-3 bi bi-arrow-90deg-left text-dark  text-light' %>
<div class="container rounded p-2 ">
    <div class="row">
        <div class="col offset-1 m-3 ">

            <h1>
                <%= "#{@user.name}" %>
                <%= "(#{@user.role.name})"%> 
            </h1>

            <p>
                <%= @user.email%>
            </p>
            <p>
                <%= @user.phone%>
            </p>
            <p>
                <%= @user.address%>
            </p>

            <%= button_to 'Remove', admin_user_path(@user), method: 'delete',class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' } if current_user.role_id == 1 || 3 %>

            <%= link_to 'Edit', edit_admin_user_path(@user), class:'btn btn-outline-primary mt-3' if current_user.role_id == 1 || 3%>
        </div>
    </div>
</div>